### ISSUE TITLE
800154 - DLT360: EU-Regulation Lobbying

### ISSUE THREAD

**Issue by DLT360-Guilherme** [DLT360/Catalyst_Reporting#13]
### Challenge: Lobbying for favorable legislation
>Ideascale Link: https://cardano.ideascale.com/c/idea/399817

## Linked Projects
- #XX 

## Project Team
- Team Member 1
- Team Member 2

### Ideascale Project Scope
> Our proposal is about delivering specific inputs to regulatory frameworks within the European Union during Q3 / 2022, utilising the great opportunities in areas, where the EU is interested in receiving commentary feedback from domain experts (Financial, Data Privacy, Competition Regulations). We can do this very effectively and efficiently by applying the continuously growing knowledge captured in our DLT360 Risk & Opportunity Radar. This way we are not starting from the scratch, but are systematically building upon the growing information from inside and outside the Cardano Community, from the continuously reviewed academic papers and from the knowledge of excellent domain experts within our network. DLT360 is a long-term-oriented project. All topics, also the regulatory and legal ones, are approached in an inter-disciplinary way.

## Cost Structure
> Based on our listed key-activities and key-resources, we plan with the following costs (please note that we are in progress of setting up a formal company body and need to calculate with taxation according to applicable law):

- Project Management (20 hours for USD 50/h = USD 1.000)
- Back-office work (50 hours for USD 20/h = USD 1.000)
- Legal research & information integration (70 hours for USD 50/h) = USD 3.500
- Writing specific commentaries (100 hours for USD 75/h) = USD 7.500
- Quality checking by domain experts (10 hours for USD 100/h) = USD 1.000
- Meetings, workshops and interactions on EU-level (50 hours for USD 100/h) = USD 5.000
- Final reporting support by domain experts, including pre and after-work (10 hours for USD 100/h) = USD 1.000

## Roadmap, Milestones and Deliverables
> This project requires the following specific key-activities - all during Q3 / 2022

- Regulation Monitoring & interaction - Financial Regulation
- Regulation Monitoring & interaction - AML requirements (Anti Money Laundering)
- Regulation Monitoring & interaction - GDPR and Blockchain
- Monitoring and realising all opportunities to engage in Commission consultations 

## KPI Progress and Success Measurement
- KPI 1: Progress of work as outlined (0-100%)
- KPI 2: Number of new (registered) EU-Legislation-related contact persons (number)
- KPI 3: Number of new (registered) EU-Legislation-related partner-organizations (number)
- KPI 4: Number of written submissions (number)

## Updated Definition of Done
> Description
- [x] Establishment of Institute for Blockchain Policy and Law with senior partners in Brussels - basis for future lobbying efforts
- [x] Establishment of IBPL Website
- [x] First 3 Foundational Research Publications of IBPL
- [ ] Primers on Financial Regulation, AML, GDPR & Blockchain
- [ ] Created monitoring mechanism for Commission consultations related to Blockchain

## Milestone Plan
1-
2-
3-
4-
5-

**Comment by DLT360-Guilherme** [comment]
## 2022/06

> Google Forms Link: https://www.dropbox.com/s/k6wbg0sof4fv83m/800154_202206.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/09

> Google Forms Link: https://www.dropbox.com/s/xtndeftfq6wxybd/800154_202209.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/10

> Google Forms Link: https://www.dropbox.com/s/v3n41nf0irp8gn3/800154_202210.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/11

> Google Forms Link: https://www.dropbox.com/s/0qw9bgtx7790kp1/800154_202211.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/12

> Google Forms Link: https://www.dropbox.com/s/bjzaqzxw0t6v1fw/800154_202212.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2023/01

> Google Forms Link: https://www.dropbox.com/s/j2pzko9ewalhoe6/800154_202301.pdf?dl=0
