### ISSUE TITLE
800153 - DLT360: DID/ZKP & GDPR-Data Privacy

### ISSUE THREAD

**Issue by DLT360-Guilherme** [DLT360/Catalyst_Reporting#15]
### Challenge: Accelerate Decentralized Identity
>Ideascale Link: https://cardano.ideascale.com/c/idea/399832

## Linked Projects
- #XX 

## Project Team
- Team Member 1
- Team Member 2

### Ideascale Project Scope
> Fund 7 has funded our DLT360 proposal called 'DID Application Blueprint'. When we started to work on this project, we ran into a very hot and emotional discussions between blockchain proponents and EU-data-privacy enthusiasts. While Blockchain proponents tend to downplay the critical conflict between blockchain and GDPR (EU-Personal Data Privacy regulation) and with the major PbD (Privacy-by-Design) principles of the GDPR, we see a big need to outline reliable approaches for public permissionless blockchains (many current compliance approaches are focused on applying private permissioned blockchains).
>Our ambition is to summarise solid best practice solution-approaches, which are specifically considering the newly emerging scalability approaches of CARDANO, with HYDRA, Sidechains, ZKP (Zero Knowledge Proof) as well as anonymisation / storage of pseudonymous data. The result will be an add-on to our Fund 7 DID Implementation Blueprint and will be properly captured in our DLT360 Risk & Opportunity Radar. We consider this highly important for all the projects starting to implement DID technology, as wrong approaches are difficult to correct later-on in a development journey.

## Cost Structure
> Based on our listed key-activities and key-resources, we plan with the following costs (please note that we are in progress of setting up a formal company body and need to calculate with taxation according to applicable law):

- Overall project management, updates on MIRO (10 hours for USD 50/h) = USD 500,00
- Communication, social media and back-office support (20 hours for USD 25/h) = USD 500,00
- Various expert meetings & discussions & travel (100 hours for average USD 80/h plus travel) = USD 10.000
- Basic research and summarising findings in add-on document to Fund 7 Blueprint (100 hours for average USD 80/h) = USD 8.000
- Supporting DLT360 RADAR and WEBsite integration (20 hours for USD 50/h) = USD 1.000,00
- Supporting the integration into the DLT360 quarterly reporting (10 hours for USD 50/h) = USD 500,00
- Active role in DLT360 quarterly roundtrip-reporting video (10 hours for USD 50/h) = USD 500,00
- Active role in sharing/discussing the content during the current quarter (50 hours for USD 80/h) = USD 4.000,00

## Roadmap, Milestones and Deliverables
> This proposal is driven by the Economy/Business Team of DLT360. This project requires the following specific key-activities - all during Q3 / 2022:

- Participation in the 2-weekly meetings of DLT360 Economy/Business Team
- Active efforts to integrate other projects and cooperation-partners
- Active cooperation with ATALA Prism team
- Synchronizing with our Fund 7 proposal (DID Application Blueprint)
- Basic research and summarizing findings in add-on document to Fund 7 Blueprint
- Supporting DLT360 RADAR and WEB-site integration
- Active role in sharing/discussing the content during the current quarter

## KPI Progress and Success Measurement
- KPI 1: Progress of activities as outlined above (0-100%)
- KPI 2: Number of partners and interacting projects / initiatives (number).
- KPI 3: Number of regulatory partners/organizations interacting with us (number)
- KPI 4: Ratings (NPS)

## Updated Definition of Done
> Deliverables:
- [x] Blockchain and GDPR Foundational Research Paper by IBPL
- [ ] DID and GDPR Memo - includes: Risk and Opportunity Summary; Subject specific presentations and summaries
- [ ] Pre-partnerships with Profila, Atala prism, Proofspace?
- [ ] IBPL Seminar preparation for cohort (DID & Data Privacy)
- [x] Integration of content into DLT360 Navigator

## Milestone Plan
1-
2-
3-
4-
5-

**Comment by DLT360-Guilherme** [comment]
## 2022/06

> Google Forms Link: https://www.dropbox.com/s/nkkm9mt5rzruxci/800153_202206.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/09

> Google Forms Link: https://www.dropbox.com/s/18tfn7z377ael2d/800153_202209.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/10

> Google Forms Link: https://www.dropbox.com/s/57d0qbjjjaz4qoq/800153_202210.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/11

> Google Forms Link: https://www.dropbox.com/s/t6cgm0elvr9wnue/800153_202211.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/12

> Google Forms Link: https://www.dropbox.com/s/6gif2lwub2wt1mo/800153_202212.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2023/01

> Google Forms Link: https://www.dropbox.com/s/c3eroijaaow5b9l/800153_202301.pdf?dl=0
