### ISSUE TITLE
700258 - Transforming Regulatory Risks

### ISSUE THREAD

**Issue by DLT360-Guilherme** [DLT360/Catalyst_Reporting#2]
### Challenge: Lobbying for Favorable Legislation
>Ideascale Link: https://cardano.ideascale.com/c/idea/384318

## Linked Projects
- #13 

## Project Team
- Jonas Weinberger
- Michiel Van Roey
- Maury Shenk

### Ideascale Project Scope
> This proposal allows us to integrate the legal and regulatory findings of various Catalyst projects into our DLT360 Risk & Opportunity Radar (funded in fund 6, see our WEB-Site). On the one hand this provides a clear overview and visualization. On the other hand this is contextualizing legal aspects in a complete and inter-disciplinary way, so that we can directly utilize these findings for the Catalyst-community's risk (and opportunity) management.

## Cost Structure
- Project Management (20 hours for USD 50/h = USD 1.000)
- Back-office work (50 hours for USD 20/h = USD 1.000)
- Legal research & information integration (70 hours for USD 50/h = USD 3.500)
- Quality checking by domain experts (10 hours for USD 100/h = USD 1.000)
- Final reporting support by domain experts, including pre and after-work (5 hours for USD 200/h = USD 1.000)
> This list of cost is not including the work of Heinz Gassner (contributed by Heinz at this early stage of the DLT360 startup).

## Roadmap, Milestones and Deliverables
> Roadmap, milestones and deliverables are linked with the progress of our DLT360 Risk & Opportunity Radar implementation (basic setup funded by fund6). Please find below the major activities and milestones for this project. Due to the linkage with other activities of the DLT360 Risk & Opportunity Radar and the lack of a graphics-integration in IDEAscale, all details are maintained in our MIRO environment. The plan below is just an orientational overview-listing:

- JAN/FEB 2022 Getting started, project formation
- FEB, MAR 2022. Phase 1 of basic content retrieval, focus on quick-win overview, coordination with other projects
- MAR 2022 Phase 1 Risk & Opportunity Radar integration, quality checking
- 3-Months MILESTONE / Deliverable: Part of Risk & Opportunity Radar - MVP reporting (draft version)
- APR-JUN 2022 Phase 2, deepening of content
- MAY-JUN 2022. Phase 2 Risk & Opportunity Radar integration, quality checking
- 6-Months MILESTONE / Deliverable: Part of Risk & Opportunity Radar - MVP reporting (final version)
- 12-Months Success: We see this as integral part of our quarterly DLT360 reporting to the community

## KPI Progress and Success Measurement
> In order to smoothly integrate this into the running DLT 360 Risk & Opportunity Radar roadmap, we will introduce 2 iterations of our project. Iteration 1 will focus on very quick wins and get this regulatory content already into our March 2022 presentation milestone (was set as part of our fund 6 project). This will of course only be rather rudimentary regulatory content, but will allow us to learn and consider feedback before going into the second iteration.

- Iteration 1 from JAN/FEB to MAR 2022
KPI 1: Content & collaborations & experts in place (0-100%)
KPI 2: Quality checks for contents packages, integration, reporting (0-100%)
KPI 3: Radar-tool and reporting integration progress (0-100%)
KPI 4: Presentation feedback NPS (1-10)

- Iteration 2 from APR to JUN 2022
KPI 1: Content & collaborations & experts in place (0-100%)
KPI 2: Quality checks for contents packages, integration, reporting (0-100%)
KPI 3: Radar-tool and reporting integration progress (0-100%)
KPI 4: Presentation feedback NPS (1-10)

## Updated Definition of Done
> Description
- [ ] DLT360 Navigator - Legal Segment:
- [ ] Smart and Legal Contracts
- [ ] DAOs and Company Law
- [ ] Data Privacy
- [ ] Financial Regulation and Securities
- [ ] AML
- [ ] Cybersecurity
- [ ] Antitrust
- [ ] IP
- [ ] Taxation

## Milestone Plan
1-
2-
3-
4-
5-

**Comment by DLT360-Guilherme** [comment]
## 09/2022

> Google Forms Link: www.xxx.com/xx
- **Project Status:** Still In Progress
- **On track?:** No 
> Why not on track?: Getting now finally back on track.
As described in earlier reports, we decided to halt all our content-creation in June 2022 (also this project) for completely relaunching our teams, work-processes and tools. We did this for  making sure that our foundations are strong enough for supporting the rather big, complex and inter-disciplinary activities we are establishing. We complete this re-launch now by end of September (we can say: 'we lost one quarter', but we are very happy with the archived results when looking into the mid-and longer term future). Happy to share this in more detail soon.

##Expected Completion
-In the next Month
## Monthly Activity: 
> Current Status (Executive Summary)
- Completion (0-100%): 
- Funding Consumption (0-100%): 
- Return of Intention (0-100%): 
- NPS Feedback (if applicable):

1. Reviewing of the result of phase 1 before June 2022 (where we did the pre-work in MIRO and in our original SaaS-Tool licensed from ITONICS).

2. Bi-weekly working-group sessions (under the guidance of our domain experts Maury Shenk and Michiel Van Roey) and active work by our regulatory workstream team with Jonas Weinberger, Victor Cabral and 3 student contributions between these review sessions.

3. Implementation of the refined REGULATORY and LAW structure into our new GitHub structure, thus becoming the input to the automatically generated DLT360 NAVIGATOR.

4. Reviewing this new structure regarding completeness and defining the processes for elaborating future content and for keeping all content up-to-date (which is one of the main goals of all our workstreams)

5. Starting to identify potential gaps, compare with our initially outlined deliverables and make a concept for closing report and closing video (we will then close a number of our projects in one closing round, because this allows us to better demonstrate the inter-disciplinary character of our work and the future role of our individual projects within the DLT360 NAVIGATOR, the DLT360 Risk & Opportunity RADAR and our future DLT360 WEB3.0 Innovation Accelerator Program).

> We plan to present the closeout of this project during October 2022.

- **Evidence:** Link/ Uploads

**Comment by DLT360-Guilherme** [comment]
## 2022/05

> Google Forms Link: https://www.dropbox.com/s/xu8s5nh61vfkgu7/700258_202205.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/06

> Google Forms Link: https://www.dropbox.com/s/77916ijzd468stx/700258_202206.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/09

> Google Forms Link: https://www.dropbox.com/s/5ozl19m7f4cf5lq/700258_202209.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/10

> Google Forms Link: https://www.dropbox.com/s/exnjprq3z06vy2h/700258_202210.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/11

> Google Forms Link: https://www.dropbox.com/s/vofydzz51e2jpeu/700258_202211.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/12

> Google Forms Link: https://www.dropbox.com/s/kxeknq0ha066yxi/700258_202212.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2023/01

> Google Forms Link: https://www.dropbox.com/s/lfz1gqv49bvst7l/700258_202301.pdf?dl=0
