### ISSUE TITLE
700112 - EU-Compliant DAO Blueprint

### ISSUE THREAD

**Issue by DLT360-Guilherme** [DLT360/Catalyst_Reporting#5]
### Challenge: DAOs ♥ Cardano
>Ideascale Link: https://cardano.ideascale.com/c/idea/384327

## Linked Projects
- #XX 

## Project Team
- Jonas Weinberger
- Victor Cabral
- Michiel Van Roey
- Maury Shenk

### Ideascale Project Scope
> As a natural consequence of establishing Smart Contracts and decentralized applications, we will see many decentralized autonomous organisations (DAO) arising. On the one hand this is required for qualifying as overall decentralized solution, on the other hand this is entering into very new regulatory terrain. Based on our DLT360 accessible knowledge, we want to develop a EU-regulation-compliant and inter-disciplinary DAO-Blueprint for doing things right from the very beginning.

## Cost Structure
> We make sure to void redundancies by partnering and integrating as many elements form other initiatives as possible. By networking with universities, active students and alumni, we are approaching our projects in a very cost-conscious way. Based on our listed key-activities and key-resources, we plan with the following costs (please note that we are in progress of setting up a formal company body and need to follow the strict European tax regulations):

- Project Management (50 hours for USD 50/h = USD 2.500)
- Backoffice work (125 hours for USD 20/h = USD 2.500)
- Legal research: Major parts handled in form of student-internship arrangement (USD 5.000)
- Analysis and establishing the BLUEPRINT document (200 hours for USD 50/h = USD 10.000)
- Quality checking by domain experts (40 hours for USD 100/h = USD 4.000)
- Final reporting support by senior domain experts, including pre and after-work (5 hours for USD 200/h = USD 1.000)

## Roadmap, Milestones and Deliverables
> Due to the strong linkage with other activities of the DLT360 and the lacking graphics-integration in IDEAscale, all details are maintained in our MIRO environment. The plan below is just an orientational overview-listing:

- FEB 2022 Getting started, project formation
- FEB -MAR 2022 Design of research, scouting for synergies with other projects, quality check of research design
- 3-Months MILESTONE: Ready for starting with legal research
- MAR - JUN 2022 Basic research
- JUN - AUG 2022. Analysis, establishing blueprint and also integration into Risk & Opportunity Radar, quality check
- 6-Months MILESTONE: First complete (draft) version of Blueprint available, one pilot DAO ready to test
- 12-Months Success: > 25 DAOs having used / planning to use the Blueprint (pipeline status)

## KPI Progress and Success Measurement
- KPI 1: Progress of required inter-disciplinary research (0-100 %)
- KPI 2: Progress of establishing the DAO BLUEPRINT (0-100%)
- KPI 3: Quality-check and community-feedback score (0-100%)
- KP! 4: Timely identification of pilot DAO (yes/no)
- KPI 5: Number of candidate-DAOs for applying the BLUEPRINT (number)
- KPI 6: Number of consulting entities planning to apply the BLUEPRINT

## Updated Definition of Done
> Description
- [x] DAOs and Company Law Foundational Research Paper by IBPL 
- [ ] DAO Legal and Compliance Issues Memo - includes: Risk and Opportunity Summary; Subject specific presentations and summaries
- [ ] Interactions with ClearContracts
- [ ] Integration of content into DLT360 Navigator

## Milestone Plan
1-
2-
3-
4-
5-

**Comment by DLT360-Guilherme** [comment]
## 2022/05

> Google Forms Link: https://www.dropbox.com/s/q4gh2j1db2lc6dw/700112_202205.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/06

> Google Forms Link: https://www.dropbox.com/s/bcnl1455cqmcy77/700112_202206.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/09

> Google Forms Link: https://www.dropbox.com/s/ygva7kl7q9hv3e2/700112_202209.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/10

> Google Forms Link: https://www.dropbox.com/s/4a3dgaonjiv2mrm/700112_202210.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/11

> Google Forms Link: https://www.dropbox.com/s/ltqes4y1tu7au48/700112_202211.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2022/12

> Google Forms Link: https://www.dropbox.com/s/zmc73x1ocn0gw1d/700112_202212.pdf?dl=0

**Comment by DLT360-Guilherme** [comment]
## 2023/01

> Google Forms Link: https://www.dropbox.com/s/z1gsmdbh578evc7/700112_202301.pdf?dl=0
